In [8]:
import numpy as np

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [5]:
import warnings
warnings.filterwarnings('ignore')
#warnings.filterwarnings(action, message='', category=Warning, module='', lineno=0, append=False)

## **Chapter3 The NumPy Library**

The NumPy library is based on one main object: `ndarray` (which stands for N-dimensional array). This object is a multidimensional, homogeneous array with a predetermined number of items: homogeneous because virtually all the items in it are of the same type and the same size.

each ndarray is associated with only one type of dtype.
The number of the dimensions and items in an array is defined by its shape, a tuple of N-positive integers that specifies the size for each dimension. The dimensions are defined as axes and the number of axes as rank.

- Create an Array

In [14]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [9]:
c = np.array([[1, 2, 3],[4, 5, 6]]) #create through a list or sequence of lists as arguments to the array() function.
c

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
d = np.array(((1, 2, 3),(4, 5, 6))) #The array() function, in addition to lists, can accept tuples and sequences of tuples.
d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
e = np.array([(1, 2, 3), [4, 5, 6], (7, 8, 9)]) #It can also accept sequences of tuples and interconnected lists.
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- type

In [19]:
type(a)
print(type(a))

numpy.ndarray

<class 'numpy.ndarray'>


In [20]:
a.dtype

dtype('int64')

In [23]:
b = np.array([[1.3, 2.4],[0.3, 4.1]])
b
b.ndim
b.size
b.shape

array([[1.3, 2.4],
       [0.3, 4.1]])

2

4

(2, 2)